apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: celery-autoscale
spec:
  replicas: 1
  selector: { matchLabels: { app: redis } }
  template:
    metadata: { labels: { app: redis } }
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports: [{ containerPort: 6379 }]
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits: { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: celery-autoscale
spec:
  selector: { app: redis }
  ports: [{ name: redis, port: 6379, targetPort: 6379 }]
