apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: celery-autoscale
data:
  config.yaml: |
    rules:
      external:
      - seriesQuery: 'celery_queue_depth'
        resources:
          overrides:
            namespace:
              resource: namespace
        name:
          matches: "^(.*)"
          as: "${1}"
        metricsQuery: 'sum(<<.Series>>{namespace="celery-autoscale"})'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: celery-autoscale
spec:
  replicas: 1
  selector: { matchLabels: { app: prometheus-adapter } }
  template:
    metadata: { labels: { app: prometheus-adapter } }
    spec:
      containers:
      - name: adapter
        image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.2
        args:
        - --config=/etc/adapter/config.yaml
        - --metrics-relist-interval=1m
        - --prometheus-url=http://prometheus.celery-autoscale.svc.cluster.local:9090
        volumeMounts: [{ name: config, mountPath: /etc/adapter }]
      volumes: [{ name: config, configMap: { name: adapter-config } }]
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: celery-autoscale
spec:
  selector: { app: prometheus-adapter }
  ports: [{ name: https, port: 443, targetPort: 6443 }]
