apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-worker-hpa
  namespace: celery-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-worker
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - { type: Percent, value: 200, periodSeconds: 15 }
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - { type: Percent, value: 50, periodSeconds: 30 }
  metrics:
  - type: External
    external:
      metric: { name: celery_queue_depth }
      target: { type: AverageValue, averageValue: "10" }
