name: Build & Push Images

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_APP: ${{ github.repository }}/celery-autoscale-app
  IMAGE_EXPORTER: ${{ github.repository }}/celery-queue-exporter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: app
            context: .
            dockerfile: app/Dockerfile
            image: ${{ env.IMAGE_APP }}
          - name: exporter
            context: .
            dockerfile: exporter/Dockerfile
            image: ${{ env.IMAGE_EXPORTER }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Derive tags
        id: tags
        run: |
          echo "sha=${GITHUB_SHA::12}" >> "$GITHUB_OUTPUT"
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "latest=latest" >> "$GITHUB_OUTPUT"
          fi
      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.image }}:${{ steps.tags.outputs.sha }}
            ${{ env.REGISTRY }}/${{ matrix.image }}:${{ steps.tags.outputs.latest || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
