name: Build & Push Images

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: app
            context: .
            dockerfile: app/Dockerfile
            image_name: celery-autoscale-app
          - name: exporter
            context: .
            dockerfile: exporter/Dockerfile
            image_name: celery-queue-exporter

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive tags
        id: tags
        run: |
          echo "sha=${GITHUB_SHA::12}" >> "$GITHUB_OUTPUT"
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "is_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_main=false" >> "$GITHUB_OUTPUT"
          fi

      # Always push the short-SHA tag
      - name: Build & Push ${{ matrix.name }} (sha)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          provenance: false
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_name }}:${{ steps.tags.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # On main, also push :latest
      - name: Tag latest for ${{ matrix.name }}
        if: steps.tags.outputs.is_main == 'true'
